import os
import sys
import time
import json
import cv2
import numpy as np

# Ensure project root is in sys.path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from config.settings import settings
from camera.stream import VideoStream
from tracking.tracker import VehicleTracker
from identity import IdentityPipeline
from schemas.event import DetectionEvent

def run_e2e_pipeline_test(max_events: int = 3, max_frames: int = 150):
    print("=" * 68)
    print("      TRAFFIX AI — END-TO-END PIPELINE INTEGRATION TEST      ")
    print("=" * 68)
    print("Flow: Video -> YOLO Detection -> BoT-SORT Track -> IdentityPipeline (ANPR+ReID)")
    print("=" * 68)

    video_path = settings.VIDEO_SOURCE
    if not os.path.exists(video_path):
        print(f"[ERROR] Video file missing at {video_path}")
        return

    # 1. Initialize complete pipeline
    print("[1/3] Initializing IdentityPipeline and VehicleTracker...")
    identity_pipeline = IdentityPipeline()
    tracker = VehicleTracker(camera_id=settings.CAMERA_ID, identity_pipeline=identity_pipeline)
    stream = VideoStream(source=video_path, loop=False)

    captured_events = []
    frame_count = 0
    start_time = time.time()

    print(f"\n[2/3] Processing frames from '{video_path}'...")
    try:
        for frame, frame_num, timestamp_sec in stream.read_frames():
            frame_count += 1

            # Update tracker & lifecycle
            _ = tracker.update(frame, frame_num=frame_num, timestamp_sec=timestamp_sec)

            # Check if any consolidated events have been generated
            events = tracker.track_manager.get_dispatchable_events()
            for event in events:
                captured_events.append(event)
                print(f"  🚗 Emitted DetectionEvent: {event.local_track_id} "
                      f"(Type: {event.vehicle_type}, Plate: {event.plate_number}, Emb: {len(event.vehicle_embedding)}D)")

            if len(captured_events) >= max_events or frame_count >= max_frames:
                break

    finally:
        stream.release()

    elapsed = time.time() - start_time
    print(f"\n[3/3] Validating Captured DetectionEvents ({len(captured_events)} emitted in {frame_count} frames)...")
    assert len(captured_events) > 0, "No DetectionEvents were generated by the pipeline!"

    for idx, event in enumerate(captured_events, 1):
        print(f"\n--- Verifying Event #{idx} ({event.local_track_id}) ---")
        
        # 1. Check Event ID
        assert event.event_id.startswith("evt_"), f"Invalid event_id: {event.event_id}"
        print(f"  • Event ID             : {event.event_id} (✅ Valid UUID)")

        # 2. Check Camera & Track IDs
        assert event.camera_id == settings.CAMERA_ID
        assert event.local_track_id.startswith(f"{settings.CAMERA_ID}_T_")
        print(f"  • Camera / Track ID    : {event.camera_id} / {event.local_track_id} (✅ Valid)")

        # 3. Check Re-ID Embedding
        assert len(event.vehicle_embedding) == settings.REID_EMBEDDING_DIM, (
            f"Expected {settings.REID_EMBEDDING_DIM}-dim embedding, got {len(event.vehicle_embedding)}"
        )
        l2_norm = np.linalg.norm(event.vehicle_embedding)
        assert abs(l2_norm - 1.0) < 1e-2, f"Embedding not normalized: {l2_norm}"
        print(f"  • Vehicle Embedding    : {len(event.vehicle_embedding)} floats, L2 norm={l2_norm:.4f} (✅ Valid)")
        print(f"  • Embedding Metadata   : {event.embedding_model} v{event.embedding_version}")

        # 4. Check Plate Data
        print(f"  • License Plate        : {event.plate_number} (Conf: {event.plate_confidence})")

        # 5. Check JSON Serialization (Guarantees Backend Compatibility)
        json_payload = event.model_dump_json()
        parsed_dict = json.loads(json_payload)
        assert "event_id" in parsed_dict
        assert "camera_id" in parsed_dict
        assert "vehicle_embedding" in parsed_dict
        print(f"  • JSON Contract Payload: {len(json_payload)} bytes serialized (✅ Valid)")

    fps_effective = frame_count / elapsed if elapsed > 0 else 0
    print("\n" + "=" * 68)
    print(f"🎉 END-TO-END PIPELINE TEST PASSED! ({frame_count} frames @ {fps_effective:.1f} FPS)")
    print("=" * 68)

if __name__ == "__main__":
    run_e2e_pipeline_test()
